### PR TITLE
Unpack original ZIP file

### PR DESCRIPTION
**Pull request by sneumann**
Hi, this is merely the unpacked testdata, so that it better fits the github philosophy, e.g. linking to particular files or even code lines.  
Yours, Steffen

### CODE REVIEW

**Comment by stuchalk** [comment]
Steffen, thanks for this PR.  Review of this is on my to do list and will be addressed this week...

**Comment by sumpfralle** [comment]
Indeed, an unpacked set of data would make it easier to reference specific files.

Thanks for your consideration!

**Comment by stuchalk** [comment]
Although the PR has not be merged, the folder of test files (now named differently) has been added to the repo.  Apologies for the slow action on this.

**Review by stuchalk — COMMENTED** [review]
This makes sense.  Has been done outside of this PR.

**Pull request closed without merging**
